apiVersion: v1
kind: Service
metadata:
  name: productapp-service

spec:
   selector:
     app: productapp
   type: LoadBalancer
   ports:
   - protocol: TCP
     port: 5000
     targetPort: 3000
     nodePort: 31120
